### ISSUE TITLE
Store - store 추가 안되는 부분 개선

### ISSUE THREAD

**Issue by reasonSun** [f-lab-edu/quing#78]
## 작업내용
store 추가 안되는 부분 개선

**Comment by chanwooo** [comment]
현재 스토어생성 -> 스토어매니저(스토어id) 순으로 생성되는것을
스토어매니저 생성 -> 로그인한 스토어매니저 권한으로 스토어 생성되도록 바꿔야할거같아요.

스토어매니저가 생성될때 store id가 require인것을 optional로 변경하고
스토어를 생성할때 스토어 매니저의 store id를 업데이트 해줘야할거같아요.

스토어 매니저 가입 -> 스토어 매니저 로그인 -> 스토어 생성 -> 스토어 관리 (메뉴 등..)
이런 순서로 가야할거같은데 처음에 이렇게 하지 않았던 이유가 있었던거같은데 기억이 잘 .. 안나네요.
별문제없으면 이런식으로 수정해보려구요
